<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8O3g9TService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.8O3g9_t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8O3g9_t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'user' => ['privates', '.errored..service_locator.8O3g9_t.Mautic\\UserBundle\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.8O3g9_t": it references class "Mautic\\UserBundle\\Entity\\User" but no such service exists.'],
        ], [
            'user' => 'Mautic\\UserBundle\\Entity\\User',
        ]);
    }
}
