<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IWlsaIiService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.IWlsaIi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IWlsaIi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'broadcastQuery' => ['services', 'mautic.sms.broadcast.query', 'getMautic_Sms_Broadcast_QueryService', true],
            'cacheStorageHelper' => ['services', 'mautic.helper.cache_storage', 'getMautic_Helper_CacheStorageService', false],
        ], [
            'broadcastQuery' => '?',
            'cacheStorageHelper' => '?',
        ]);
    }
}
