<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBroadcastSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\EventListener\BroadcastSubscriber' shared autowired service.
     *
     * @return \Mautic\EmailBundle\EventListener\BroadcastSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\EmailBundle\\Model\\EmailModel'] ?? $container->getEmailModelService());

        if (isset($container->services['Mautic\\EmailBundle\\EventListener\\BroadcastSubscriber'])) {
            return $container->services['Mautic\\EmailBundle\\EventListener\\BroadcastSubscriber'];
        }

        return $container->services['Mautic\\EmailBundle\\EventListener\\BroadcastSubscriber'] = new \Mautic\EmailBundle\EventListener\BroadcastSubscriber($a, ($container->services['mautic.permission.manager'] ?? $container->getMautic_Permission_ManagerService()), ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
