<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryRepositoryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CategoryBundle\Entity\CategoryRepository' shared autowired service.
     *
     * @return \Mautic\CategoryBundle\Entity\CategoryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CategoryBundle\\Entity\\CategoryRepository'] = new \Mautic\CategoryBundle\Entity\CategoryRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
