<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChannelSubscriber2Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\DynamicContentBundle\EventListener\ChannelSubscriber' shared autowired service.
     *
     * @return \Mautic\DynamicContentBundle\EventListener\ChannelSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\DynamicContentBundle\\EventListener\\ChannelSubscriber'] = new \Mautic\DynamicContentBundle\EventListener\ChannelSubscriber();
    }
}
