<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCitrixActionTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticCitrixBundle\Form\Type\CitrixActionType' shared autowired service.
     *
     * @return \MauticPlugin\MauticCitrixBundle\Form\Type\CitrixActionType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\FormBundle\\Model\\FieldModel'] ?? $container->getFieldModelService());

        if (isset($container->services['MauticPlugin\\MauticCitrixBundle\\Form\\Type\\CitrixActionType'])) {
            return $container->services['MauticPlugin\\MauticCitrixBundle\\Form\\Type\\CitrixActionType'];
        }

        return $container->services['MauticPlugin\\MauticCitrixBundle\\Form\\Type\\CitrixActionType'] = new \MauticPlugin\MauticCitrixBundle\Form\Type\CitrixActionType($a);
    }
}
