<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetermineWinnerSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\AssetBundle\EventListener\DetermineWinnerSubscriber' shared autowired service.
     *
     * @return \Mautic\AssetBundle\EventListener\DetermineWinnerSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->services['Mautic\\AssetBundle\\EventListener\\DetermineWinnerSubscriber'])) {
            return $container->services['Mautic\\AssetBundle\\EventListener\\DetermineWinnerSubscriber'];
        }

        return $container->services['Mautic\\AssetBundle\\EventListener\\DetermineWinnerSubscriber'] = new \Mautic\AssetBundle\EventListener\DetermineWinnerSubscriber($a, ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
