<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardBestHoursSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\EventListener\DashboardBestHoursSubscriber' shared autowired service.
     *
     * @return \Mautic\EmailBundle\EventListener\DashboardBestHoursSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\EmailBundle\\Model\\EmailModel'] ?? $container->getEmailModelService());

        if (isset($container->services['Mautic\\EmailBundle\\EventListener\\DashboardBestHoursSubscriber'])) {
            return $container->services['Mautic\\EmailBundle\\EventListener\\DashboardBestHoursSubscriber'];
        }

        return $container->services['Mautic\\EmailBundle\\EventListener\\DashboardBestHoursSubscriber'] = new \Mautic\EmailBundle\EventListener\DashboardBestHoursSubscriber($a);
    }
}
