<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDynamicContentTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\DynamicContentBundle\Form\Type\DynamicContentType' shared autowired service.
     *
     * @return \Mautic\DynamicContentBundle\Form\Type\DynamicContentType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\ListModel'] ?? $container->getListModelService());

        if (isset($container->services['Mautic\\DynamicContentBundle\\Form\\Type\\DynamicContentType'])) {
            return $container->services['Mautic\\DynamicContentBundle\\Form\\Type\\DynamicContentType'];
        }
        $b = ($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? $container->getLeadModelService());

        if (isset($container->services['Mautic\\DynamicContentBundle\\Form\\Type\\DynamicContentType'])) {
            return $container->services['Mautic\\DynamicContentBundle\\Form\\Type\\DynamicContentType'];
        }

        return $container->services['Mautic\\DynamicContentBundle\\Form\\Type\\DynamicContentType'] = new \Mautic\DynamicContentBundle\Form\Type\DynamicContentType(($container->services['mautic.permission.manager'] ?? $container->getMautic_Permission_ManagerService()), $a, ($container->services['translator'] ?? $container->getTranslator2Service()), $b);
    }
}
