<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExcelExporterService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\ReportBundle\Model\ExcelExporter' shared autowired service.
     *
     * @return \Mautic\ReportBundle\Model\ExcelExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\ReportBundle\\Model\\ExcelExporter'] = new \Mautic\ReportBundle\Model\ExcelExporter(($container->services['mautic.helper.twig.formatter'] ?? $container->getMautic_Helper_Twig_FormatterService()), ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
