<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormSubmitActionUserEmailTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\Form\Type\FormSubmitActionUserEmailType' shared autowired service.
     *
     * @return \Mautic\EmailBundle\Form\Type\FormSubmitActionUserEmailType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\EmailBundle\\Form\\Type\\FormSubmitActionUserEmailType'] = new \Mautic\EmailBundle\Form\Type\FormSubmitActionUserEmailType();
    }
}
