<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIntegrationEntityRepositoryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PluginBundle\Entity\IntegrationEntityRepository' shared autowired service.
     *
     * @return \Mautic\PluginBundle\Entity\IntegrationEntityRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\PluginBundle\\Entity\\IntegrationEntityRepository'] = new \Mautic\PluginBundle\Entity\IntegrationEntityRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
