<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadSubscriber4Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\AssetBundle\EventListener\LeadSubscriber' shared autowired service.
     *
     * @return \Mautic\AssetBundle\EventListener\LeadSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\AssetBundle\\Model\\AssetModel'] ?? $container->getAssetModelService());

        if (isset($container->services['Mautic\\AssetBundle\\EventListener\\LeadSubscriber'])) {
            return $container->services['Mautic\\AssetBundle\\EventListener\\LeadSubscriber'];
        }
        $b = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->services['Mautic\\AssetBundle\\EventListener\\LeadSubscriber'])) {
            return $container->services['Mautic\\AssetBundle\\EventListener\\LeadSubscriber'];
        }

        return $container->services['Mautic\\AssetBundle\\EventListener\\LeadSubscriber'] = new \Mautic\AssetBundle\EventListener\LeadSubscriber($a, ($container->services['translator'] ?? $container->getTranslator2Service()), $b, ($container->services['Mautic\\AssetBundle\\Entity\\DownloadRepository'] ?? $container->load('getDownloadRepositoryService')));
    }
}
