<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Helper_HashService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.helper.hash' shared service.
     *
     * @return \Mautic\CoreBundle\Helper\HashHelper\HashHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.helper.hash'] = new \Mautic\CoreBundle\Helper\HashHelper\HashHelper();
    }
}
