<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Sms_Twilio_ConfigurationService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.sms.twilio.configuration' shared service.
     *
     * @return \Mautic\SmsBundle\Integration\Twilio\Configuration
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.helper.integration'] ?? $container->getMautic_Helper_IntegrationService());

        if (isset($container->services['mautic.sms.twilio.configuration'])) {
            return $container->services['mautic.sms.twilio.configuration'];
        }

        return $container->services['mautic.sms.twilio.configuration'] = new \Mautic\SmsBundle\Integration\Twilio\Configuration($a);
    }
}
