<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMauticClearbitBundleService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticClearbitBundle\MauticClearbitBundle' shared autowired service.
     *
     * @return \MauticPlugin\MauticClearbitBundle\MauticClearbitBundle
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['MauticPlugin\\MauticClearbitBundle\\MauticClearbitBundle'] = new \MauticPlugin\MauticClearbitBundle\MauticClearbitBundle();
    }
}
