<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Lead_Columns_DictionaryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.lead.columns.dictionary' shared service.
     *
     * @return \Mautic\LeadBundle\Services\ContactColumnsDictionary
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\FieldModel'] ?? $container->getFieldModel2Service());

        if (isset($container->services['mautic.lead.columns.dictionary'])) {
            return $container->services['mautic.lead.columns.dictionary'];
        }

        return $container->services['mautic.lead.columns.dictionary'] = new \Mautic\LeadBundle\Services\ContactColumnsDictionary($a, ($container->services['translator'] ?? $container->getTranslator2Service()), ($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container))));
    }
}
