<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Integrations_Helper_FieldValidatorService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.integrations.helper.field_validator' shared service.
     *
     * @return \Mautic\IntegrationsBundle\Helper\FieldValidationHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.integrations.sync.data_exchange.mautic.field_helper'] ?? $container->load('getMautic_Integrations_Sync_DataExchange_Mautic_FieldHelperService'));

        if (isset($container->services['mautic.integrations.helper.field_validator'])) {
            return $container->services['mautic.integrations.helper.field_validator'];
        }

        return $container->services['mautic.integrations.helper.field_validator'] = new \Mautic\IntegrationsBundle\Helper\FieldValidationHelper($a, ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
