<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Form_Type_DynamicContentFilterEntryFiltersService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.form.type.dynamic_content_filter_entry_filters' shared service.
     *
     * @return \Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryFiltersType
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['mautic.form.type.dynamic_content_filter_entry_filters'] = $instance = new \Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryFiltersType(($container->services['translator'] ?? $container->getTranslator2Service()));

        $instance->setConnection(($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()));

        return $instance;
    }
}
