<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Integrations_Sync_DataExchange_Mautic_OrderExecutionerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.integrations.sync.data_exchange.mautic.order_executioner' shared service.
     *
     * @return \Mautic\IntegrationsBundle\Sync\SyncDataExchange\Internal\Executioner\OrderExecutioner
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.integrations.sync.data_exchange.mautic.order_executioner'] = new \Mautic\IntegrationsBundle\Sync\SyncDataExchange\Internal\Executioner\OrderExecutioner(($container->services['mautic.integrations.helper.sync_mapping'] ?? $container->load('getMautic_Integrations_Helper_SyncMappingService')), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['mautic.integrations.internal.object_provider'] ?? $container->load('getMautic_Integrations_Internal_ObjectProviderService')), ($container->services['mautic.integrations.internal.reference_resolver'] ?? $container->load('getMautic_Integrations_Internal_ReferenceResolverService')), ($container->services['mautic.integrations.internal.field_validator'] ?? $container->load('getMautic_Integrations_Internal_FieldValidatorService')));
    }
}
