<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Campaign_Helper_InactivityService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.campaign.helper.inactivity' shared service.
     *
     * @return \Mautic\CampaignBundle\Executioner\Helper\InactiveHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.campaign.helper.inactivity'] = new \Mautic\CampaignBundle\Executioner\Helper\InactiveHelper(($container->services['mautic.campaign.scheduler'] ?? $container->load('getMautic_Campaign_SchedulerService')), ($container->services['mautic.campaign.contact_finder.inactive'] ?? $container->load('getMautic_Campaign_ContactFinder_InactiveService')), ($container->services['mautic.campaign.repository.lead_event_log'] ?? $container->getMautic_Campaign_Repository_LeadEventLogService()), ($container->services['mautic.campaign.repository.event'] ?? $container->load('getMautic_Campaign_Repository_EventService')), ($container->services['monolog.logger.mautic'] ?? $container->getMonolog_Logger_MauticService()), ($container->services['mautic.campaign.helper.decision'] ?? $container->load('getMautic_Campaign_Helper_DecisionService')));
    }
}
