<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMauticFocusBundleService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticFocusBundle\MauticFocusBundle' shared autowired service.
     *
     * @return \MauticPlugin\MauticFocusBundle\MauticFocusBundle
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['MauticPlugin\\MauticFocusBundle\\MauticFocusBundle'] = new \MauticPlugin\MauticFocusBundle\MauticFocusBundle();
    }
}
