<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMauticPluginBundleService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PluginBundle\MauticPluginBundle' shared autowired service.
     *
     * @return \Mautic\PluginBundle\MauticPluginBundle
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\PluginBundle\\MauticPluginBundle'] = new \Mautic\PluginBundle\MauticPluginBundle();
    }
}
