<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMauticCoreBundleService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\MauticCoreBundle' shared autowired service.
     *
     * @return \Mautic\CoreBundle\MauticCoreBundle
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\MauticCoreBundle'] = new \Mautic\CoreBundle\MauticCoreBundle();
    }
}
