<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoxlogicRateLimit_OauthKeyGenerateListenerService extends AppKernelProdContainer
{
    /*
     * Gets the private 'noxlogic_rate_limit.oauth_key_generate_listener' shared service.
     *
     * @return \Noxlogic\RateLimitBundle\EventListener\OauthKeyGenerateListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['noxlogic_rate_limit.oauth_key_generate_listener'] = new \Noxlogic\RateLimitBundle\EventListener\OauthKeyGenerateListener(($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()));
    }
}
