<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPackageModelService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\MarketplaceBundle\Model\PackageModel' shared autowired service.
     *
     * @return \Mautic\MarketplaceBundle\Model\PackageModel
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\MarketplaceBundle\\Model\\PackageModel'] = new \Mautic\MarketplaceBundle\Model\PackageModel(($container->services['marketplace.api.connection'] ?? $container->load('getMarketplace_Api_ConnectionService')), ($container->services['marketplace.service.allowlist'] ?? $container->load('getMarketplace_Service_AllowlistService')));
    }
}
