<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportSchedulerSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\ReportBundle\Scheduler\EventListener\ReportSchedulerSubscriber' shared autowired service.
     *
     * @return \Mautic\ReportBundle\Scheduler\EventListener\ReportSchedulerSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.report.model.scheduler_planner'] ?? $container->load('getMautic_Report_Model_SchedulerPlannerService'));

        if (isset($container->services['Mautic\\ReportBundle\\Scheduler\\EventListener\\ReportSchedulerSubscriber'])) {
            return $container->services['Mautic\\ReportBundle\\Scheduler\\EventListener\\ReportSchedulerSubscriber'];
        }

        return $container->services['Mautic\\ReportBundle\\Scheduler\\EventListener\\ReportSchedulerSubscriber'] = new \Mautic\ReportBundle\Scheduler\EventListener\ReportSchedulerSubscriber($a);
    }
}
