<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\AssetBundle\EventListener\ReportSubscriber' shared autowired service.
     *
     * @return \Mautic\AssetBundle\EventListener\ReportSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\CompanyReportData'] ?? $container->load('getCompanyReportDataService'));

        if (isset($container->services['Mautic\\AssetBundle\\EventListener\\ReportSubscriber'])) {
            return $container->services['Mautic\\AssetBundle\\EventListener\\ReportSubscriber'];
        }

        return $container->services['Mautic\\AssetBundle\\EventListener\\ReportSubscriber'] = new \Mautic\AssetBundle\EventListener\ReportSubscriber($a, ($container->services['Mautic\\AssetBundle\\Entity\\DownloadRepository'] ?? $container->load('getDownloadRepositoryService')));
    }
}
