<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportSubscriber3Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\ChannelBundle\EventListener\ReportSubscriber' shared autowired service.
     *
     * @return \Mautic\ChannelBundle\EventListener\ReportSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->services['Mautic\\ChannelBundle\\EventListener\\ReportSubscriber'])) {
            return $container->services['Mautic\\ChannelBundle\\EventListener\\ReportSubscriber'];
        }

        return $container->services['Mautic\\ChannelBundle\\EventListener\\ReportSubscriber'] = new \Mautic\ChannelBundle\EventListener\ReportSubscriber(($container->services['Mautic\\LeadBundle\\Model\\CompanyReportData'] ?? $container->load('getCompanyReportDataService')), $a);
    }
}
