<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_Provider_LightsamlSp_MainService extends AppKernelProdContainer
{
    /*
     * Gets the private 'security.authentication.provider.lightsaml_sp.main' shared service.
     *
     * @return \LightSaml\SpBundle\Security\Authentication\Provider\LightsSamlSpAuthenticationProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.user.provider'] ?? $container->getMautic_User_ProviderService());

        if (isset($container->privates['security.authentication.provider.lightsaml_sp.main'])) {
            return $container->privates['security.authentication.provider.lightsaml_sp.main'];
        }
        $b = ($container->services['mautic.security.saml.user_creator'] ?? $container->load('getMautic_Security_Saml_UserCreatorService'));

        if (isset($container->privates['security.authentication.provider.lightsaml_sp.main'])) {
            return $container->privates['security.authentication.provider.lightsaml_sp.main'];
        }

        return $container->privates['security.authentication.provider.lightsaml_sp.main'] = new \LightSaml\SpBundle\Security\Authentication\Provider\LightsSamlSpAuthenticationProvider('main', $a, true, ($container->privates['security.user_checker'] ?? ($container->privates['security.user_checker'] = new \Symfony\Component\Security\Core\User\InMemoryUserChecker())), ($container->services['mautic.security.saml.username_mapper'] ?? $container->load('getMautic_Security_Saml_UsernameMapperService')), $b, new \LightSaml\SpBundle\Security\User\SimpleAttributeMapper(), new \LightSaml\SpBundle\Security\Authentication\Token\SamlSpTokenFactory());
    }
}
