<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSendChannelBroadcastCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\ChannelBundle\Command\SendChannelBroadcastCommand' shared autowired service.
     *
     * @return \Mautic\ChannelBundle\Command\SendChannelBroadcastCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\ChannelBundle\\Command\\SendChannelBroadcastCommand'] = new \Mautic\ChannelBundle\Command\SendChannelBroadcastCommand(($container->services['translator'] ?? $container->getTranslator2Service()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['mautic.helper.paths'] ?? $container->getMautic_Helper_PathsService()), ($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container))));
    }
}
