<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_Listener_Basic_ApiService extends AppKernelProdContainer
{
    /*
     * Gets the private 'security.authentication.listener.basic.api' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\BasicAuthenticationListener
     *
     * @deprecated Since symfony/security-bundle 5.3: The "security.authentication.listener.basic.api" service is deprecated, use the new authenticator system instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('symfony/security-bundle', '5.3', 'The "security.authentication.listener.basic.api" service is deprecated, use the new authenticator system instead.');

        $a = ($container->privates['security.authentication.manager'] ?? $container->load('getSecurity_Authentication_ManagerService'));

        if (isset($container->privates['security.authentication.listener.basic.api'])) {
            return $container->privates['security.authentication.listener.basic.api'];
        }

        $container->privates['security.authentication.listener.basic.api'] = $instance = new \Symfony\Component\Security\Http\Firewall\BasicAuthenticationListener(($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()), $a, 'api', ($container->privates['fos_oauth_server.security.entry_point'] ?? $container->load('getFosOauthServer_Security_EntryPointService')), ($container->privates['monolog.logger.security'] ?? $container->load('getMonolog_Logger_SecurityService')));

        $instance->setSessionAuthenticationStrategy(new \Symfony\Component\Security\Http\Session\SessionAuthenticationStrategy('none'));

        return $instance;
    }
}
