<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStageActionListTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\StageBundle\Form\Type\StageActionListType' shared autowired service.
     *
     * @return \Mautic\StageBundle\Form\Type\StageActionListType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\StageBundle\\Model\\StageModel'] ?? $container->load('getStageModelService'));

        if (isset($container->services['Mautic\\StageBundle\\Form\\Type\\StageActionListType'])) {
            return $container->services['Mautic\\StageBundle\\Form\\Type\\StageActionListType'];
        }

        return $container->services['Mautic\\StageBundle\\Form\\Type\\StageActionListType'] = new \Mautic\StageBundle\Form\Type\StageActionListType($a);
    }
}
