<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getThemeListTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Form\Type\ThemeListType' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Form\Type\ThemeListType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.helper.theme'] ?? $container->getMautic_Helper_ThemeService());

        if (isset($container->services['Mautic\\CoreBundle\\Form\\Type\\ThemeListType'])) {
            return $container->services['Mautic\\CoreBundle\\Form\\Type\\ThemeListType'];
        }

        return $container->services['Mautic\\CoreBundle\\Form\\Type\\ThemeListType'] = new \Mautic\CoreBundle\Form\Type\ThemeListType($a);
    }
}
