<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTriggerModelService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PointBundle\Model\TriggerModel' shared autowired service.
     *
     * @return \Mautic\PointBundle\Model\TriggerModel
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? $container->getLeadModelService());

        if (isset($container->services['Mautic\\PointBundle\\Model\\TriggerModel'])) {
            return $container->services['Mautic\\PointBundle\\Model\\TriggerModel'];
        }
        $b = ($container->services['Mautic\\PointBundle\\Model\\TriggerEventModel'] ?? $container->load('getTriggerEventModelService'));

        if (isset($container->services['Mautic\\PointBundle\\Model\\TriggerModel'])) {
            return $container->services['Mautic\\PointBundle\\Model\\TriggerModel'];
        }
        $c = ($container->services['Mautic\\CoreBundle\\Factory\\MauticFactory'] ?? $container->getMauticFactoryService());

        if (isset($container->services['Mautic\\PointBundle\\Model\\TriggerModel'])) {
            return $container->services['Mautic\\PointBundle\\Model\\TriggerModel'];
        }
        $d = ($container->services['mautic.tracker.contact'] ?? $container->getMautic_Tracker_ContactService());

        if (isset($container->services['Mautic\\PointBundle\\Model\\TriggerModel'])) {
            return $container->services['Mautic\\PointBundle\\Model\\TriggerModel'];
        }
        $e = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->services['Mautic\\PointBundle\\Model\\TriggerModel'])) {
            return $container->services['Mautic\\PointBundle\\Model\\TriggerModel'];
        }
        $f = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['Mautic\\PointBundle\\Model\\TriggerModel'])) {
            return $container->services['Mautic\\PointBundle\\Model\\TriggerModel'];
        }
        $g = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->services['Mautic\\PointBundle\\Model\\TriggerModel'])) {
            return $container->services['Mautic\\PointBundle\\Model\\TriggerModel'];
        }

        return $container->services['Mautic\\PointBundle\\Model\\TriggerModel'] = new \Mautic\PointBundle\Model\TriggerModel(($container->services['mautic.helper.ip_lookup'] ?? $container->getMautic_Helper_IpLookupService()), $a, $b, $c, $d, $e, ($container->services['mautic.security'] ?? $container->getMautic_SecurityService()), $f, $g, ($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? $container->getTranslatorService()), ($container->services['mautic.helper.user'] ?? $container->getMautic_Helper_UserService()), ($container->services['monolog.logger.mautic'] ?? $container->getMonolog_Logger_MauticService()), ($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container))));
    }
}
