<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_Z2ILDLIService extends AppKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.z2ILDLI' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['Mautic\\MessengerBundle\\MessageHandler\\TestHandler'] ?? $container->load('getTestHandlerService'));

        if (isset($container->privates['.messenger.handler_descriptor.z2ILDLI'])) {
            return $container->privates['.messenger.handler_descriptor.z2ILDLI'];
        }

        return $container->privates['.messenger.handler_descriptor.z2ILDLI'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(\Closure::fromCallable([0 => $a, 1 => 'handleEmail']), ['method' => 'handleEmail']);
    }
}
