<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4n8fp4KService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.4n8fp4K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4n8fp4K'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'model' => ['services', 'MauticPlugin\\MauticSocialBundle\\Model\\MonitoringModel', 'getMonitoringModelService', true],
        ], [
            'model' => 'MauticPlugin\\MauticSocialBundle\\Model\\MonitoringModel',
        ]);
    }
}
