<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K6Ii5YPService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.K6Ii5YP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K6Ii5YP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pageHelperFacotry' => ['services', 'mautic.page.helper.factory', 'getMautic_Page_Helper_FactoryService', true],
        ], [
            'pageHelperFacotry' => '?',
        ]);
    }
}
