<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PDJYzMService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.P_DJYzM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P_DJYzM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formAdjustmentsProvider' => ['services', 'mautic.lead.provider.formAdjustments', 'getMautic_Lead_Provider_FormAdjustmentsService', true],
            'formFactory' => ['services', '.container.private.form.factory', 'get_Container_Private_Form_FactoryService', false],
            'listModel' => ['services', 'Mautic\\LeadBundle\\Model\\ListModel', 'getListModelService', false],
        ], [
            'formAdjustmentsProvider' => '?',
            'formFactory' => '?',
            'listModel' => 'Mautic\\LeadBundle\\Model\\ListModel',
        ]);
    }
}
