<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAbortColumnCreateExceptionService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Field\Exception\AbortColumnCreateException' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Field\Exception\AbortColumnCreateException
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Field\\Exception\\AbortColumnCreateException'] = new \Mautic\LeadBundle\Field\Exception\AbortColumnCreateException();
    }
}
