<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getButtonSubscriber5Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\EventListener\ButtonSubscriber' shared autowired service.
     *
     * @return \Mautic\LeadBundle\EventListener\ButtonSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->services['Mautic\\LeadBundle\\EventListener\\ButtonSubscriber'])) {
            return $container->services['Mautic\\LeadBundle\\EventListener\\ButtonSubscriber'];
        }

        return $container->services['Mautic\\LeadBundle\\EventListener\\ButtonSubscriber'] = new \Mautic\LeadBundle\EventListener\ButtonSubscriber(($container->services['translator'] ?? $container->getTranslator2Service()), $a);
    }
}
