<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\IntegrationsBundle\Sync\SyncDataExchange\Internal\Object\Company' shared autowired service.
     *
     * @return \Mautic\IntegrationsBundle\Sync\SyncDataExchange\Internal\Object\Company
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\IntegrationsBundle\\Sync\\SyncDataExchange\\Internal\\Object\\Company'] = new \Mautic\IntegrationsBundle\Sync\SyncDataExchange\Internal\Object\Company();
    }
}
