<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Form\Type\CompanyType' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Form\Type\CompanyType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->services['Mautic\\LeadBundle\\Form\\Type\\CompanyType'])) {
            return $container->services['Mautic\\LeadBundle\\Form\\Type\\CompanyType'];
        }

        return $container->services['Mautic\\LeadBundle\\Form\\Type\\CompanyType'] = new \Mautic\LeadBundle\Form\Type\CompanyType(($container->services['mautic.permission.manager'] ?? $container->getMautic_Permission_ManagerService()), $a, ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
