<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyReportDataService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Model\CompanyReportData' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Model\CompanyReportData
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\FieldModel'] ?? $container->getFieldModel2Service());

        if (isset($container->services['Mautic\\LeadBundle\\Model\\CompanyReportData'])) {
            return $container->services['Mautic\\LeadBundle\\Model\\CompanyReportData'];
        }

        return $container->services['Mautic\\LeadBundle\\Model\\CompanyReportData'] = new \Mautic\LeadBundle\Model\CompanyReportData($a, ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
