<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigTrackingPageTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PageBundle\Form\Type\ConfigTrackingPageType' shared autowired service.
     *
     * @return \Mautic\PageBundle\Form\Type\ConfigTrackingPageType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\PageBundle\\Form\\Type\\ConfigTrackingPageType'] = new \Mautic\PageBundle\Form\Type\ConfigTrackingPageType();
    }
}
