<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignEventHelperService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CampaignBundle\Helper\CampaignEventHelper' shared autowired service.
     *
     * @return \Mautic\CampaignBundle\Helper\CampaignEventHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CampaignBundle\\Helper\\CampaignEventHelper'] = new \Mautic\CampaignBundle\Helper\CampaignEventHelper();
    }
}
