<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDynamicContentSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\DynamicContentBundle\EventListener\DynamicContentSubscriber' shared autowired service.
     *
     * @return \Mautic\DynamicContentBundle\EventListener\DynamicContentSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\PageBundle\\Model\\TrackableModel'] ?? $container->getTrackableModelService());

        if (isset($container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'])) {
            return $container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'];
        }
        $b = ($container->services['mautic.page.helper.token'] ?? $container->getMautic_Page_Helper_TokenService());

        if (isset($container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'])) {
            return $container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'];
        }
        $c = ($container->services['mautic.form.helper.token'] ?? $container->load('getMautic_Form_Helper_TokenService'));

        if (isset($container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'])) {
            return $container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'];
        }
        $d = ($container->services['mautic.focus.helper.token'] ?? $container->load('getMautic_Focus_Helper_TokenService'));

        if (isset($container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'])) {
            return $container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'];
        }
        $e = ($container->services['Mautic\\CoreBundle\\Model\\AuditLogModel'] ?? $container->getAuditLogModelService());

        if (isset($container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'])) {
            return $container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'];
        }
        $f = ($container->services['mautic.helper.dynamicContent'] ?? $container->load('getMautic_Helper_DynamicContentService'));

        if (isset($container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'])) {
            return $container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'];
        }
        $g = ($container->services['Mautic\\DynamicContentBundle\\Model\\DynamicContentModel'] ?? $container->load('getDynamicContentModelService'));

        if (isset($container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'])) {
            return $container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'];
        }
        $h = ($container->services['mautic.tracker.contact'] ?? $container->getMautic_Tracker_ContactService());

        if (isset($container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'])) {
            return $container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'];
        }

        return $container->services['Mautic\\DynamicContentBundle\\EventListener\\DynamicContentSubscriber'] = new \Mautic\DynamicContentBundle\EventListener\DynamicContentSubscriber($a, $b, ($container->services['Mautic\\AssetBundle\\Helper\\TokenHelper'] ?? $container->getTokenHelperService()), $c, $d, $e, $f, $g, ($container->services['mautic.security'] ?? $container->getMautic_SecurityService()), $h);
    }
}
