<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDetermineWinnerSubscriber3Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\FormBundle\EventListener\DetermineWinnerSubscriber' shared autowired service.
     *
     * @return \Mautic\FormBundle\EventListener\DetermineWinnerSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\FormBundle\\EventListener\\DetermineWinnerSubscriber'] = new \Mautic\FormBundle\EventListener\DetermineWinnerSubscriber(($container->services['Mautic\\FormBundle\\Entity\\SubmissionRepository'] ?? $container->load('getSubmissionRepositoryService')), ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
