<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFieldAliasToFqcnMapService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Form\FieldAliasToFqcnMap' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Form\FieldAliasToFqcnMap
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Form\\FieldAliasToFqcnMap'] = new \Mautic\LeadBundle\Form\FieldAliasToFqcnMap();
    }
}
