<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedbackLoopNotFoundService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\MonitoredEmail\Exception\FeedbackLoopNotFound' shared autowired service.
     *
     * @return \Mautic\EmailBundle\MonitoredEmail\Exception\FeedbackLoopNotFound
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\EmailBundle\\MonitoredEmail\\Exception\\FeedbackLoopNotFound'] = new \Mautic\EmailBundle\MonitoredEmail\Exception\FeedbackLoopNotFound();
    }
}
