<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvalidTransportService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\Mailer\Transport\InvalidTransport' shared autowired service.
     *
     * @return \Mautic\EmailBundle\Mailer\Transport\InvalidTransport
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\EmailBundle\\Mailer\\Transport\\InvalidTransport'] = new \Mautic\EmailBundle\Mailer\Transport\InvalidTransport();
    }
}
