<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIntegrationCampaignsTaskTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticCrmBundle\Form\Type\IntegrationCampaignsTaskType' shared autowired service.
     *
     * @return \MauticPlugin\MauticCrmBundle\Form\Type\IntegrationCampaignsTaskType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.integration.connectwise'] ?? $container->load('getMautic_Integration_ConnectwiseService'));

        if (isset($container->services['MauticPlugin\\MauticCrmBundle\\Form\\Type\\IntegrationCampaignsTaskType'])) {
            return $container->services['MauticPlugin\\MauticCrmBundle\\Form\\Type\\IntegrationCampaignsTaskType'];
        }

        return $container->services['MauticPlugin\\MauticCrmBundle\\Form\\Type\\IntegrationCampaignsTaskType'] = new \MauticPlugin\MauticCrmBundle\Form\Type\IntegrationCampaignsTaskType($a);
    }
}
