<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIntegrationRequestSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticCitrixBundle\EventListener\IntegrationRequestSubscriber' shared autowired service.
     *
     * @return \MauticPlugin\MauticCitrixBundle\EventListener\IntegrationRequestSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['MauticPlugin\\MauticCitrixBundle\\EventListener\\IntegrationRequestSubscriber'] = new \MauticPlugin\MauticCitrixBundle\EventListener\IntegrationRequestSubscriber();
    }
}
