<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadListAccessService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Form\Validator\Constraints\LeadListAccess' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Form\Validator\Constraints\LeadListAccess
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Form\\Validator\\Constraints\\LeadListAccess'] = new \Mautic\LeadBundle\Form\Validator\Constraints\LeadListAccess();
    }
}
