<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Lead_Field_Dispatcher_FieldColumnBackgroundDispatcherService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.lead.field.dispatcher.field_column_background_dispatcher' shared service.
     *
     * @return \Mautic\LeadBundle\Field\Dispatcher\FieldColumnBackgroundJobDispatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.lead.field.dispatcher.field_column_background_dispatcher'] = new \Mautic\LeadBundle\Field\Dispatcher\FieldColumnBackgroundJobDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
