<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Helper_CommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.helper.command' shared service.
     *
     * @return \Mautic\CoreBundle\Helper\CommandHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.helper.command'] = new \Mautic\CoreBundle\Helper\CommandHelper(($container->services['kernel'] ?? $container->get('kernel', 1)));
    }
}
