<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Campaign_Executioner_InactiveService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.campaign.executioner.inactive' shared service.
     *
     * @return \Mautic\CampaignBundle\Executioner\InactiveExecutioner
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.campaign.executioner.inactive'] = new \Mautic\CampaignBundle\Executioner\InactiveExecutioner(($container->services['mautic.campaign.contact_finder.inactive'] ?? $container->load('getMautic_Campaign_ContactFinder_InactiveService')), ($container->services['monolog.logger.mautic'] ?? $container->getMonolog_Logger_MauticService()), ($container->services['translator'] ?? $container->getTranslator2Service()), ($container->services['mautic.campaign.scheduler'] ?? $container->load('getMautic_Campaign_SchedulerService')), ($container->services['mautic.campaign.helper.inactivity'] ?? $container->load('getMautic_Campaign_Helper_InactivityService')), ($container->services['mautic.campaign.event_executioner'] ?? $container->load('getMautic_Campaign_EventExecutionerService')));
    }
}
