<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Integrations_Helper_CompanyObjectService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.integrations.helper.company_object' shared service.
     *
     * @return \Mautic\IntegrationsBundle\Sync\SyncDataExchange\Internal\ObjectHelper\CompanyObjectHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\CompanyModel'] ?? $container->getCompanyModelService());

        if (isset($container->services['mautic.integrations.helper.company_object'])) {
            return $container->services['mautic.integrations.helper.company_object'];
        }
        $b = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->services['mautic.integrations.helper.company_object'])) {
            return $container->services['mautic.integrations.helper.company_object'];
        }

        return $container->services['mautic.integrations.helper.company_object'] = new \Mautic\IntegrationsBundle\Sync\SyncDataExchange\Internal\ObjectHelper\CompanyObjectHelper($a, ($container->services['mautic.lead.repository.company'] ?? $container->getMautic_Lead_Repository_CompanyService()), $b);
    }
}
