<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Helper_NotificationService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.helper.notification' shared service.
     *
     * @return \Mautic\NotificationBundle\Helper\NotificationHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->services['mautic.helper.notification'])) {
            return $container->services['mautic.helper.notification'];
        }
        $b = ($container->services['Mautic\\CoreBundle\\Twig\\Helper\\AssetsHelper'] ?? $container->getAssetsHelperService());

        if (isset($container->services['mautic.helper.notification'])) {
            return $container->services['mautic.helper.notification'];
        }
        $c = ($container->services['mautic.helper.integration'] ?? $container->getMautic_Helper_IntegrationService());

        if (isset($container->services['mautic.helper.notification'])) {
            return $container->services['mautic.helper.notification'];
        }
        $d = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->services['mautic.helper.notification'])) {
            return $container->services['mautic.helper.notification'];
        }

        return $container->services['mautic.helper.notification'] = new \Mautic\NotificationBundle\Helper\NotificationHelper($a, $b, ($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container))), $c, $d, ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->services['Mautic\\LeadBundle\\Model\\DoNotContact'] ?? $container->getDoNotContactService()));
    }
}
