<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Maxmind_DoNotSellListService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.maxmind.doNotSellList' shared service.
     *
     * @return \Mautic\CoreBundle\IpLookup\DoNotSellList\MaxMindDoNotSellList
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.maxmind.doNotSellList'] = new \Mautic\CoreBundle\IpLookup\DoNotSellList\MaxMindDoNotSellList(($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container))));
    }
}
