<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Campaign_Service_CampaignService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.campaign.service.campaign' shared service.
     *
     * @return \Mautic\CampaignBundle\Service\Campaign
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.campaign.repository.campaign'] ?? $container->load('getMautic_Campaign_Repository_CampaignService'));

        if (isset($container->services['mautic.campaign.service.campaign'])) {
            return $container->services['mautic.campaign.service.campaign'];
        }
        $b = ($container->services['mautic.email.repository.email'] ?? $container->load('getMautic_Email_Repository_EmailService'));

        if (isset($container->services['mautic.campaign.service.campaign'])) {
            return $container->services['mautic.campaign.service.campaign'];
        }

        return $container->services['mautic.campaign.service.campaign'] = new \Mautic\CampaignBundle\Service\Campaign($a, $b);
    }
}
