<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMarketplace_Api_ConnectionService extends AppKernelProdContainer
{
    /*
     * Gets the public 'marketplace.api.connection' shared service.
     *
     * @return \Mautic\MarketplaceBundle\Api\Connection
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['marketplace.api.connection'] = new \Mautic\MarketplaceBundle\Api\Connection(($container->services['mautic.http.client'] ?? ($container->services['mautic.http.client'] = new \GuzzleHttp\Client())), ($container->services['monolog.logger.mautic'] ?? $container->getMonolog_Logger_MauticService()));
    }
}
