<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonitoringTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticSocialBundle\Form\Type\MonitoringType' shared autowired service.
     *
     * @return \MauticPlugin\MauticSocialBundle\Form\Type\MonitoringType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['MauticPlugin\\MauticSocialBundle\\Model\\MonitoringModel'] ?? $container->load('getMonitoringModelService'));

        if (isset($container->services['MauticPlugin\\MauticSocialBundle\\Form\\Type\\MonitoringType'])) {
            return $container->services['MauticPlugin\\MauticSocialBundle\\Form\\Type\\MonitoringType'];
        }

        return $container->services['MauticPlugin\\MauticSocialBundle\\Form\\Type\\MonitoringType'] = new \MauticPlugin\MauticSocialBundle\Form\Type\MonitoringType($a);
    }
}
