<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Integrations_Sync_InternalProcessService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.integrations.sync.internal_process' shared service.
     *
     * @return \Mautic\IntegrationsBundle\Sync\SyncProcess\Direction\Internal\MauticSyncProcess
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.integrations.sync.internal_process'] = new \Mautic\IntegrationsBundle\Sync\SyncProcess\Direction\Internal\MauticSyncProcess(($container->services['mautic.integrations.helper.sync_date'] ?? $container->load('getMautic_Integrations_Helper_SyncDateService')), ($container->services['mautic.integrations.sync.internal_process.object_change_generator'] ?? $container->load('getMautic_Integrations_Sync_InternalProcess_ObjectChangeGeneratorService')));
    }
}
