<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Form_Type_FormSubmitactionSendemailService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.form.type.form_submitaction_sendemail' shared service.
     *
     * @return \Mautic\FormBundle\Form\Type\SubmitActionEmailType
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['mautic.form.type.form_submitaction_sendemail'] = $instance = new \Mautic\FormBundle\Form\Type\SubmitActionEmailType(($container->services['translator'] ?? $container->getTranslator2Service()), ($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container))));

        $instance->setFieldModel(($container->services['Mautic\\FormBundle\\Model\\FieldModel'] ?? $container->getFieldModelService()));
        $instance->setFormModel(($container->services['Mautic\\FormBundle\\Model\\FormModel'] ?? $container->getFormModelService()));

        return $instance;
    }
}
