<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationRepositoryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Entity\NotificationRepository' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Entity\NotificationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Entity\\NotificationRepository'] = new \Mautic\CoreBundle\Entity\NotificationRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
