<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPluginRepositoryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PluginBundle\Entity\PluginRepository' shared autowired service.
     *
     * @return \Mautic\PluginBundle\Entity\PluginRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\PluginBundle\\Entity\\PluginRepository'] = new \Mautic\PluginBundle\Entity\PluginRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
