<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointEventHelper2Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Helper\PointEventHelper' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Helper\PointEventHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Helper\\PointEventHelper'] = new \Mautic\LeadBundle\Helper\PointEventHelper();
    }
}
