<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReplySubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\SmsBundle\EventListener\ReplySubscriber' shared autowired service.
     *
     * @return \Mautic\SmsBundle\EventListener\ReplySubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\SmsBundle\\EventListener\\ReplySubscriber'] = new \Mautic\SmsBundle\EventListener\ReplySubscriber(($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? $container->getTranslatorService()), ($container->services['Mautic\\LeadBundle\\Entity\\LeadEventLogRepository'] ?? $container->load('getLeadEventLogRepository2Service')));
    }
}
