<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScheduleIsValidService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\ReportBundle\Scheduler\Validator\ScheduleIsValid' shared autowired service.
     *
     * @return \Mautic\ReportBundle\Scheduler\Validator\ScheduleIsValid
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\ReportBundle\\Scheduler\\Validator\\ScheduleIsValid'] = new \Mautic\ReportBundle\Scheduler\Validator\ScheduleIsValid();
    }
}
