<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTableOrderTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\ReportBundle\Form\Type\TableOrderType' shared autowired service.
     *
     * @return \Mautic\ReportBundle\Form\Type\TableOrderType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\ReportBundle\\Form\\Type\\TableOrderType'] = new \Mautic\ReportBundle\Form\Type\TableOrderType(($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
