<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateDoNotSellListCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Command\UpdateDoNotSellListCommand' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Command\UpdateDoNotSellListCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Command\\UpdateDoNotSellListCommand'] = new \Mautic\CoreBundle\Command\UpdateDoNotSellListCommand(($container->services['mautic.helper.maxmind_do_not_sell_download'] ?? $container->load('getMautic_Helper_MaxmindDoNotSellDownloadService')), ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
