<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateIpDataStoreCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Command\UpdateIpDataStoreCommand' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Command\UpdateIpDataStoreCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Command\\UpdateIpDataStoreCommand'] = new \Mautic\CoreBundle\Command\UpdateIpDataStoreCommand(($container->services['translator'] ?? $container->getTranslator2Service()), ($container->services['mautic.ip_lookup'] ?? $container->getMautic_IpLookupService()));
    }
}
