<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVariantType2Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PageBundle\Form\Type\VariantType' shared autowired service.
     *
     * @return \Mautic\PageBundle\Form\Type\VariantType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\PageBundle\\Model\\PageModel'] ?? $container->getPageModelService());

        if (isset($container->services['Mautic\\PageBundle\\Form\\Type\\VariantType'])) {
            return $container->services['Mautic\\PageBundle\\Form\\Type\\VariantType'];
        }

        return $container->services['Mautic\\PageBundle\\Form\\Type\\VariantType'] = new \Mautic\PageBundle\Form\Type\VariantType($a);
    }
}
