<?php

namespace ContainerTJJPQO2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebhookSubscriber2Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\FormBundle\EventListener\WebhookSubscriber' shared autowired service.
     *
     * @return \Mautic\FormBundle\EventListener\WebhookSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\WebhookBundle\\Model\\WebhookModel'] ?? $container->load('getWebhookModelService'));

        if (isset($container->services['Mautic\\FormBundle\\EventListener\\WebhookSubscriber'])) {
            return $container->services['Mautic\\FormBundle\\EventListener\\WebhookSubscriber'];
        }

        return $container->services['Mautic\\FormBundle\\EventListener\\WebhookSubscriber'] = new \Mautic\FormBundle\EventListener\WebhookSubscriber($a);
    }
}
