<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5Rax088Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.5Rax088' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5Rax088'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'contactTracker' => ['services', 'mautic.tracker.contact', 'getMautic_Tracker_ContactService', false],
            'trackedDeviceService' => ['services', 'mautic.lead.service.device_tracking_service', 'getMautic_Lead_Service_DeviceTrackingServiceService', false],
        ], [
            'contactTracker' => '?',
            'trackedDeviceService' => '?',
        ]);
    }
}
