<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K2z8S7qService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.K2z8S7q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K2z8S7q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formFactory' => ['services', '.container.private.form.factory', 'get_Container_Private_Form_FactoryService', false],
            'monitoringModel' => ['services', 'mautic.social.model.monitoring', 'getMautic_Social_Model_MonitoringService', true],
        ], [
            'formFactory' => '?',
            'monitoringModel' => '?',
        ]);
    }
}
