<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D1JXZKlService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.d1JXZKl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d1JXZKl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ipLookupHelper' => ['services', 'mautic.helper.ip_lookup', 'getMautic_Helper_IpLookupService', false],
        ], [
            'ipLookupHelper' => '?',
        ]);
    }
}
