<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9AovCjGService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.9AovCjG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9AovCjG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'availabilityChecker' => ['services', 'mautic.focus.helper.iframe_availability_checker', 'getMautic_Focus_Helper_IframeAvailabilityCheckerService', true],
        ], [
            'availabilityChecker' => '?',
        ]);
    }
}
