<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArrayStringTransformerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Form\DataTransformer\ArrayStringTransformer' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Form\DataTransformer\ArrayStringTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Form\\DataTransformer\\ArrayStringTransformer'] = new \Mautic\CoreBundle\Form\DataTransformer\ArrayStringTransformer();
    }
}
