<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCouldNotFetchLatestVersionExceptionService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Helper\Update\Exception\CouldNotFetchLatestVersionException' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Helper\Update\Exception\CouldNotFetchLatestVersionException
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Helper\\Update\\Exception\\CouldNotFetchLatestVersionException'] = new \Mautic\CoreBundle\Helper\Update\Exception\CouldNotFetchLatestVersionException();
    }
}
