<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignReplyTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\SmsBundle\Form\Type\CampaignReplyType' shared autowired service.
     *
     * @return \Mautic\SmsBundle\Form\Type\CampaignReplyType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\SmsBundle\\Form\\Type\\CampaignReplyType'] = new \Mautic\SmsBundle\Form\Type\CampaignReplyType();
    }
}
