<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConvertConfigCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Command\ConvertConfigCommand' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Command\ConvertConfigCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Command\\ConvertConfigCommand'] = new \Mautic\CoreBundle\Command\ConvertConfigCommand(($container->services['mautic.helper.paths'] ?? $container->getMautic_Helper_PathsService()));
    }
}
