<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsumeQueueCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\QueueBundle\Command\ConsumeQueueCommand' shared autowired service.
     *
     * @return \Mautic\QueueBundle\Command\ConsumeQueueCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\QueueBundle\\Command\\ConsumeQueueCommand'] = new \Mautic\QueueBundle\Command\ConsumeQueueCommand(($container->services['mautic.queue.service'] ?? $container->getMautic_Queue_ServiceService()));
    }
}
