<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalculatorHelperService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\StatsBundle\Aggregate\Helper\CalculatorHelper' shared autowired service.
     *
     * @return \Mautic\StatsBundle\Aggregate\Helper\CalculatorHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\StatsBundle\\Aggregate\\Helper\\CalculatorHelper'] = new \Mautic\StatsBundle\Aggregate\Helper\CalculatorHelper();
    }
}
