<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignEventAddRemoveLeadTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CampaignBundle\Form\Type\CampaignEventAddRemoveLeadType' shared autowired service.
     *
     * @return \Mautic\CampaignBundle\Form\Type\CampaignEventAddRemoveLeadType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CampaignBundle\\Form\\Type\\CampaignEventAddRemoveLeadType'] = new \Mautic\CampaignBundle\Form\Type\CampaignEventAddRemoveLeadType();
    }
}
