<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDateTimeTokenSubscriber2Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PageBundle\EventListener\DateTimeTokenSubscriber' shared autowired service.
     *
     * @return \Mautic\PageBundle\EventListener\DateTimeTokenSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.tracker.contact'] ?? $container->getMautic_Tracker_ContactService());

        if (isset($container->services['Mautic\\PageBundle\\EventListener\\DateTimeTokenSubscriber'])) {
            return $container->services['Mautic\\PageBundle\\EventListener\\DateTimeTokenSubscriber'];
        }

        return $container->services['Mautic\\PageBundle\\EventListener\\DateTimeTokenSubscriber'] = new \Mautic\PageBundle\EventListener\DateTimeTokenSubscriber(($container->services['translator'] ?? $container->getTranslator2Service()), ($container->services['Mautic\\CoreBundle\\Helper\\DateTime\\DateTimeToken'] ?? $container->load('getDateTimeTokenService')), ($container->services['mautic.security'] ?? $container->getMautic_SecurityService()), $a);
    }
}
