<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDynamicContentFilterEntryTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryType' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.lead.model.list'] ?? $container->getMautic_Lead_Model_ListService());

        if (isset($container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'])) {
            return $container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'];
        }
        $b = ($container->services['mautic.stage.model.stage'] ?? $container->load('getMautic_Stage_Model_StageService'));

        if (isset($container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'])) {
            return $container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'];
        }
        $c = ($container->services['mautic.integrations.helper.builder_integrations'] ?? $container->getMautic_Integrations_Helper_BuilderIntegrationsService());

        if (isset($container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'])) {
            return $container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'];
        }

        return $container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'] = new \Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryType($a, $b, $c);
    }
}
