<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDownloadRepositoryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\AssetBundle\Entity\DownloadRepository' shared autowired service.
     *
     * @return \Mautic\AssetBundle\Entity\DownloadRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\AssetBundle\\Entity\\DownloadRepository'] = new \Mautic\AssetBundle\Entity\DownloadRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
