<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExportSchedulerCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\ReportBundle\Scheduler\Command\ExportSchedulerCommand' shared autowired service.
     *
     * @return \Mautic\ReportBundle\Scheduler\Command\ExportSchedulerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\ReportBundle\\Scheduler\\Command\\ExportSchedulerCommand'] = new \Mautic\ReportBundle\Scheduler\Command\ExportSchedulerCommand(($container->services['mautic.report.model.report_exporter'] ?? $container->load('getMautic_Report_Model_ReportExporterService')), ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
