<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailToUserSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\EventListener\EmailToUserSubscriber' shared autowired service.
     *
     * @return \Mautic\EmailBundle\EventListener\EmailToUserSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.email.model.send_email_to_user'] ?? $container->load('getMautic_Email_Model_SendEmailToUserService'));

        if (isset($container->services['Mautic\\EmailBundle\\EventListener\\EmailToUserSubscriber'])) {
            return $container->services['Mautic\\EmailBundle\\EventListener\\EmailToUserSubscriber'];
        }

        return $container->services['Mautic\\EmailBundle\\EventListener\\EmailToUserSubscriber'] = new \Mautic\EmailBundle\EventListener\EmailToUserSubscriber($a);
    }
}
