<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailEventsService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\EmailEvents' shared autowired service.
     *
     * @return \Mautic\EmailBundle\EmailEvents
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\EmailBundle\\EmailEvents'] = new \Mautic\EmailBundle\EmailEvents();
    }
}
