<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFileEncodingValidatorService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Form\Validator\Constraints\FileEncodingValidator' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Form\Validator\Constraints\FileEncodingValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.lead.model.list'] ?? $container->getMautic_Lead_Model_ListService());

        if (isset($container->services['Mautic\\CoreBundle\\Form\\Validator\\Constraints\\FileEncodingValidator'])) {
            return $container->services['Mautic\\CoreBundle\\Form\\Validator\\Constraints\\FileEncodingValidator'];
        }
        $b = ($container->services['mautic.helper.field.alias'] ?? $container->load('getMautic_Helper_Field_AliasService'));

        if (isset($container->services['Mautic\\CoreBundle\\Form\\Validator\\Constraints\\FileEncodingValidator'])) {
            return $container->services['Mautic\\CoreBundle\\Form\\Validator\\Constraints\\FileEncodingValidator'];
        }

        return $container->services['Mautic\\CoreBundle\\Form\\Validator\\Constraints\\FileEncodingValidator'] = new \Mautic\CoreBundle\Form\Validator\Constraints\FileEncodingValidator($a, $b);
    }
}
