<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticFocusBundle\EventListener\FormSubscriber' shared autowired service.
     *
     * @return \MauticPlugin\MauticFocusBundle\EventListener\FormSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.focus.model.focus'] ?? $container->getMautic_Focus_Model_FocusService());

        if (isset($container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\FormSubscriber'])) {
            return $container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\FormSubscriber'];
        }

        return $container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\FormSubscriber'] = new \MauticPlugin\MauticFocusBundle\EventListener\FormSubscriber($a);
    }
}
