<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportContactSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\EventListener\ImportContactSubscriber' shared autowired service.
     *
     * @return \Mautic\LeadBundle\EventListener\ImportContactSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? $container->getLeadModelService());

        if (isset($container->services['Mautic\\LeadBundle\\EventListener\\ImportContactSubscriber'])) {
            return $container->services['Mautic\\LeadBundle\\EventListener\\ImportContactSubscriber'];
        }

        return $container->services['Mautic\\LeadBundle\\EventListener\\ImportContactSubscriber'] = new \Mautic\LeadBundle\EventListener\ImportContactSubscriber(($container->services['mautic.lead.field.field_list'] ?? $container->getMautic_Lead_Field_FieldListService()), ($container->services['mautic.security'] ?? $container->getMautic_SecurityService()), $a, ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
