<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIntegrationCampaignsTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PluginBundle\Form\Type\IntegrationCampaignsType' shared autowired service.
     *
     * @return \Mautic\PluginBundle\Form\Type\IntegrationCampaignsType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\PluginBundle\\Form\\Type\\IntegrationCampaignsType'] = new \Mautic\PluginBundle\Form\Type\IntegrationCampaignsType();
    }
}
