<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportCompanySubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\EventListener\ImportCompanySubscriber' shared autowired service.
     *
     * @return \Mautic\LeadBundle\EventListener\ImportCompanySubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.lead.model.company'] ?? $container->getMautic_Lead_Model_CompanyService());

        if (isset($container->services['Mautic\\LeadBundle\\EventListener\\ImportCompanySubscriber'])) {
            return $container->services['Mautic\\LeadBundle\\EventListener\\ImportCompanySubscriber'];
        }

        return $container->services['Mautic\\LeadBundle\\EventListener\\ImportCompanySubscriber'] = new \Mautic\LeadBundle\EventListener\ImportCompanySubscriber(($container->services['mautic.lead.field.field_list'] ?? $container->getMautic_Lead_Field_FieldListService()), ($container->services['mautic.security'] ?? $container->getMautic_SecurityService()), $a, ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
