<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Asset_PermissionsService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.asset.permissions' shared service.
     *
     * @return \Mautic\AssetBundle\Security\Permissions\AssetPermissions
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.asset.permissions'] = new \Mautic\AssetBundle\Security\Permissions\AssetPermissions(($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container))));
    }
}
