<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Plugin_Facade_ReloadService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.plugin.facade.reload' shared service.
     *
     * @return \Mautic\PluginBundle\Facade\ReloadFacade
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.plugin.model.plugin'] ?? $container->getMautic_Plugin_Model_PluginService());

        if (isset($container->services['mautic.plugin.facade.reload'])) {
            return $container->services['mautic.plugin.facade.reload'];
        }
        $b = ($container->services['mautic.plugin.helper.reload'] ?? $container->load('getMautic_Plugin_Helper_ReloadService'));

        if (isset($container->services['mautic.plugin.facade.reload'])) {
            return $container->services['mautic.plugin.facade.reload'];
        }

        return $container->services['mautic.plugin.facade.reload'] = new \Mautic\PluginBundle\Facade\ReloadFacade($a, $b, ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
