<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Email_FetcherService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.email.fetcher' shared service.
     *
     * @return \Mautic\EmailBundle\MonitoredEmail\Fetcher
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.email.fetcher'] = new \Mautic\EmailBundle\MonitoredEmail\Fetcher(($container->services['mautic.helper.mailbox'] ?? $container->getMautic_Helper_MailboxService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
