<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Cache_ClearCacheSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.cache.clear_cache_subscriber' shared service.
     *
     * @return \Mautic\CacheBundle\EventListener\CacheClearSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.cache.clear_cache_subscriber'] = new \Mautic\CacheBundle\EventListener\CacheClearSubscriber(($container->services['mautic.cache.provider'] ?? $container->getMautic_Cache_ProviderService()), ($container->services['monolog.logger.mautic'] ?? $container->getMonolog_Logger_MauticService()));
    }
}
