<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Sms_Twilio_CallbackService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.sms.twilio.callback' shared service.
     *
     * @return \Mautic\SmsBundle\Integration\Twilio\TwilioCallback
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.sms.twilio.callback'] = new \Mautic\SmsBundle\Integration\Twilio\TwilioCallback(($container->services['mautic.sms.helper.contact'] ?? $container->load('getMautic_Sms_Helper_ContactService')), ($container->services['mautic.sms.twilio.configuration'] ?? $container->load('getMautic_Sms_Twilio_ConfigurationService')));
    }
}
