<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Install_LeadcolumnsService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.install.leadcolumns' shared service.
     *
     * @return \Mautic\InstallBundle\EventListener\DoctrineEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.install.leadcolumns'] = new \Mautic\InstallBundle\EventListener\DoctrineEventSubscriber();
    }
}
