<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Queue_Helper_RabbitmqConsumerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.queue.helper.rabbitmq_consumer' shared service.
     *
     * @return \Mautic\QueueBundle\Helper\RabbitMqConsumer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.queue.helper.rabbitmq_consumer'] = new \Mautic\QueueBundle\Helper\RabbitMqConsumer(($container->services['mautic.queue.service'] ?? $container->getMautic_Queue_ServiceService()));
    }
}
