<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Integrations_Internal_ObjectProviderService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.integrations.internal.object_provider' shared service.
     *
     * @return \Mautic\IntegrationsBundle\Sync\SyncDataExchange\Internal\ObjectProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['mautic.integrations.internal.object_provider'])) {
            return $container->services['mautic.integrations.internal.object_provider'];
        }

        return $container->services['mautic.integrations.internal.object_provider'] = new \Mautic\IntegrationsBundle\Sync\SyncDataExchange\Internal\ObjectProvider($a);
    }
}
