<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Email_Model_SendEmailToUserService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.email.model.send_email_to_user' shared service.
     *
     * @return \Mautic\EmailBundle\Model\SendEmailToUser
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.email.model.email'] ?? $container->getMautic_Email_Model_EmailService());

        if (isset($container->services['mautic.email.model.send_email_to_user'])) {
            return $container->services['mautic.email.model.send_email_to_user'];
        }
        $b = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['mautic.email.model.send_email_to_user'])) {
            return $container->services['mautic.email.model.send_email_to_user'];
        }
        $c = ($container->services['mautic.validator.email'] ?? $container->getMautic_Validator_EmailService());

        if (isset($container->services['mautic.email.model.send_email_to_user'])) {
            return $container->services['mautic.email.model.send_email_to_user'];
        }

        return $container->services['mautic.email.model.send_email_to_user'] = new \Mautic\EmailBundle\Model\SendEmailToUser($a, $b, ($container->services['mautic.lead.validator.custom_field'] ?? $container->load('getMautic_Lead_Validator_CustomFieldService')), $c);
    }
}
