<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Report_Model_FileHandlerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.report.model.file_handler' shared service.
     *
     * @return \Mautic\ReportBundle\Scheduler\Model\FileHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.report.model.file_handler'] = new \Mautic\ReportBundle\Scheduler\Model\FileHandler(($container->services['mautic.helper.file_path_resolver'] ?? $container->getMautic_Helper_FilePathResolverService()), ($container->services['mautic.helper.file_properties'] ?? ($container->services['mautic.helper.file_properties'] = new \Mautic\CoreBundle\Helper\FileProperties())), ($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container))));
    }
}
