<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Message_Processor_ReplierService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.message.processor.replier' shared service.
     *
     * @return \Mautic\EmailBundle\MonitoredEmail\Processor\Reply
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? $container->getLeadModelService());

        if (isset($container->services['mautic.message.processor.replier'])) {
            return $container->services['mautic.message.processor.replier'];
        }
        $b = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['mautic.message.processor.replier'])) {
            return $container->services['mautic.message.processor.replier'];
        }
        $c = ($container->services['mautic.tracker.contact'] ?? $container->getMautic_Tracker_ContactService());

        if (isset($container->services['mautic.message.processor.replier'])) {
            return $container->services['mautic.message.processor.replier'];
        }

        return $container->services['mautic.message.processor.replier'] = new \Mautic\EmailBundle\MonitoredEmail\Processor\Reply(($container->services['mautic.email.repository.stat'] ?? $container->getMautic_Email_Repository_StatService()), ($container->services['mautic.message.search.contact'] ?? $container->load('getMautic_Message_Search_ContactService')), $a, $b, ($container->services['monolog.logger.mautic'] ?? $container->getMonolog_Logger_MauticService()), $c, ($container->services['Mautic\\CoreBundle\\Helper\\EmailAddressHelper'] ?? ($container->services['Mautic\\CoreBundle\\Helper\\EmailAddressHelper'] = new \Mautic\CoreBundle\Helper\EmailAddressHelper())));
    }
}
