<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Report_Model_ReportExporterService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.report.model.report_exporter' shared service.
     *
     * @return \Mautic\ReportBundle\Model\ReportExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.report.model.report_exporter'] = new \Mautic\ReportBundle\Model\ReportExporter(($container->services['mautic.report.model.schedule_model'] ?? $container->load('getMautic_Report_Model_ScheduleModelService')), ($container->services['mautic.report.model.report_data_adapter'] ?? $container->load('getMautic_Report_Model_ReportDataAdapterService')), ($container->services['mautic.report.model.report_export_options'] ?? $container->load('getMautic_Report_Model_ReportExportOptionsService')), ($container->services['mautic.report.model.report_file_writer'] ?? $container->load('getMautic_Report_Model_ReportFileWriterService')), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
    }
}
