<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Helper_DynamicContentService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.helper.dynamicContent' shared service.
     *
     * @return \Mautic\DynamicContentBundle\Helper\DynamicContentHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.dynamicContent.model.dynamicContent'] ?? $container->load('getMautic_DynamicContent_Model_DynamicContentService'));

        if (isset($container->services['mautic.helper.dynamicContent'])) {
            return $container->services['mautic.helper.dynamicContent'];
        }
        $b = ($container->services['mautic.campaign.executioner.realtime'] ?? $container->load('getMautic_Campaign_Executioner_RealtimeService'));

        if (isset($container->services['mautic.helper.dynamicContent'])) {
            return $container->services['mautic.helper.dynamicContent'];
        }
        $c = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->services['mautic.helper.dynamicContent'])) {
            return $container->services['mautic.helper.dynamicContent'];
        }
        $d = ($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? $container->getLeadModelService());

        if (isset($container->services['mautic.helper.dynamicContent'])) {
            return $container->services['mautic.helper.dynamicContent'];
        }

        return $container->services['mautic.helper.dynamicContent'] = new \Mautic\DynamicContentBundle\Helper\DynamicContentHelper($a, $b, $c, $d);
    }
}
