<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Sync_LoggerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.sync.logger' shared service.
     *
     * @return \Mautic\IntegrationsBundle\Sync\Logger\DebugLogger
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.sync.logger'] = new \Mautic\IntegrationsBundle\Sync\Logger\DebugLogger(($container->services['monolog.logger.mautic'] ?? $container->getMonolog_Logger_MauticService()));
    }
}
