<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Integrations_Sync_Notification_HandlerContactService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.integrations.sync.notification.handler_contact' shared service.
     *
     * @return \Mautic\IntegrationsBundle\Sync\Notification\Handler\ContactNotificationHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.integrations.sync.notification.handler_contact'] = new \Mautic\IntegrationsBundle\Sync\Notification\Handler\ContactNotificationHandler(($container->services['mautic.integrations.sync.notification.writer'] ?? $container->load('getMautic_Integrations_Sync_Notification_WriterService')), ($container->services['mautic.lead.repository.lead_event_log'] ?? $container->load('getMautic_Lead_Repository_LeadEventLogService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['mautic.integrations.sync.notification.helper_user_summary_notification'] ?? $container->load('getMautic_Integrations_Sync_Notification_HelperUserSummaryNotificationService')));
    }
}
