<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Category_Model_Contact_ActionService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.category.model.contact.action' shared service.
     *
     * @return \Mautic\CategoryBundle\Model\ContactActionModel
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.category.model.contact.action'] = new \Mautic\CategoryBundle\Model\ContactActionModel(($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? $container->getLeadModelService()));
    }
}
