<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Sms_Broadcast_QueryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.sms.broadcast.query' shared service.
     *
     * @return \Mautic\SmsBundle\Broadcast\BroadcastQuery
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->services['mautic.sms.broadcast.query'])) {
            return $container->services['mautic.sms.broadcast.query'];
        }
        $b = ($container->services['mautic.sms.model.sms'] ?? $container->load('getMautic_Sms_Model_SmsService'));

        if (isset($container->services['mautic.sms.broadcast.query'])) {
            return $container->services['mautic.sms.broadcast.query'];
        }

        return $container->services['mautic.sms.broadcast.query'] = new \Mautic\SmsBundle\Broadcast\BroadcastQuery($a, $b);
    }
}
