<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMauticFormBundleService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\FormBundle\MauticFormBundle' shared autowired service.
     *
     * @return \Mautic\FormBundle\MauticFormBundle
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\FormBundle\\MauticFormBundle'] = new \Mautic\FormBundle\MauticFormBundle();
    }
}
