<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMergeValueHelperService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Deduplicate\Helper\MergeValueHelper' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Deduplicate\Helper\MergeValueHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Deduplicate\\Helper\\MergeValueHelper'] = new \Mautic\LeadBundle\Deduplicate\Helper\MergeValueHelper();
    }
}
