<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Integrations_Sync_Notification_BulkNotificationService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.integrations.sync.notification.bulk_notification' shared service.
     *
     * @return \Mautic\IntegrationsBundle\Sync\Notification\BulkNotification
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.integrations.sync.notification.bulk_notification'] = new \Mautic\IntegrationsBundle\Sync\Notification\BulkNotification(($container->services['mautic.core.service.bulk_notification'] ?? $container->load('getMautic_Core_Service_BulkNotificationService')), ($container->services['mautic.integrations.sync.notification.user_notification_builder'] ?? $container->load('getMautic_Integrations_Sync_Notification_UserNotificationBuilderService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
