<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Messenger_Config_SubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.messenger.config.subscriber' shared service.
     *
     * @return \Mautic\MessengerBundle\EventListener\ConfigSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.messenger.config.subscriber'] = new \Mautic\MessengerBundle\EventListener\ConfigSubscriber(($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container))), ($container->services['mautic.messenger.transport_type'] ?? ($container->services['mautic.messenger.transport_type'] = new \Mautic\MessengerBundle\Model\MessengerTransportType())));
    }
}
