<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_FailedDefaultService extends AppKernelProdContainer
{
    /*
     * Gets the private 'messenger.transport.failed_default' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['messenger.transport_factory'] ?? $container->load('getMessenger_TransportFactoryService'));

        if (isset($container->privates['messenger.transport.failed_default'])) {
            return $container->privates['messenger.transport.failed_default'];
        }

        return $container->privates['messenger.transport.failed_default'] = $a->createTransport($container->getEnv('MAUTIC_MESSENGER_TRANSPORT_DSN'), ['table_name' => 'messenger_failed_default', 'transport_name' => 'failed_default'], ($container->privates['messenger.transport.native_php_serializer'] ?? ($container->privates['messenger.transport.native_php_serializer'] = new \Symfony\Component\Messenger\Transport\Serialization\PhpSerializer())));
    }
}
