<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Form_Helper_TokenService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.form.helper.token' shared service.
     *
     * @return \Mautic\FormBundle\Helper\TokenHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.form.model.form'] ?? $container->getMautic_Form_Model_FormService());

        if (isset($container->services['mautic.form.helper.token'])) {
            return $container->services['mautic.form.helper.token'];
        }

        return $container->services['mautic.form.helper.token'] = new \Mautic\FormBundle\Helper\TokenHelper($a, ($container->services['mautic.security'] ?? $container->getMautic_SecurityService()));
    }
}
