<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Form_Helper_Properties_AccessorService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.form.helper.properties.accessor' shared service.
     *
     * @return \Mautic\FormBundle\Helper\PropertiesAccessor
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.form.model.form'] ?? $container->getMautic_Form_Model_FormService());

        if (isset($container->services['mautic.form.helper.properties.accessor'])) {
            return $container->services['mautic.form.helper.properties.accessor'];
        }

        return $container->services['mautic.form.helper.properties.accessor'] = new \Mautic\FormBundle\Helper\PropertiesAccessor($a);
    }
}
