<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPointActionHelperService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\AssetBundle\Helper\PointActionHelper' shared autowired service.
     *
     * @return \Mautic\AssetBundle\Helper\PointActionHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\AssetBundle\\Helper\\PointActionHelper'] = new \Mautic\AssetBundle\Helper\PointActionHelper();
    }
}
