<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPluginHandledFilterExceptionService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Segment\Exception\PluginHandledFilterException' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Segment\Exception\PluginHandledFilterException
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Segment\\Exception\\PluginHandledFilterException'] = new \Mautic\LeadBundle\Segment\Exception\PluginHandledFilterException();
    }
}
