<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPreferenceCenterListTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PageBundle\Form\Type\PreferenceCenterListType' shared autowired service.
     *
     * @return \Mautic\PageBundle\Form\Type\PreferenceCenterListType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.page.model.page'] ?? $container->getMautic_Page_Model_PageService());

        if (isset($container->services['Mautic\\PageBundle\\Form\\Type\\PreferenceCenterListType'])) {
            return $container->services['Mautic\\PageBundle\\Form\\Type\\PreferenceCenterListType'];
        }

        return $container->services['Mautic\\PageBundle\\Form\\Type\\PreferenceCenterListType'] = new \Mautic\PageBundle\Form\Type\PreferenceCenterListType($a, ($container->services['mautic.security'] ?? $container->getMautic_SecurityService()));
    }
}
