<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportSubscriber4Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\EventListener\ReportSubscriber' shared autowired service.
     *
     * @return \Mautic\EmailBundle\EventListener\ReportSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->services['Mautic\\EmailBundle\\EventListener\\ReportSubscriber'])) {
            return $container->services['Mautic\\EmailBundle\\EventListener\\ReportSubscriber'];
        }
        $b = ($container->services['mautic.generated.columns.provider'] ?? $container->getMautic_Generated_Columns_ProviderService());

        if (isset($container->services['Mautic\\EmailBundle\\EventListener\\ReportSubscriber'])) {
            return $container->services['Mautic\\EmailBundle\\EventListener\\ReportSubscriber'];
        }
        $c = ($container->services['mautic.lead.reportbundle.fields_builder'] ?? $container->load('getMautic_Lead_Reportbundle_FieldsBuilderService'));

        if (isset($container->services['Mautic\\EmailBundle\\EventListener\\ReportSubscriber'])) {
            return $container->services['Mautic\\EmailBundle\\EventListener\\ReportSubscriber'];
        }

        return $container->services['Mautic\\EmailBundle\\EventListener\\ReportSubscriber'] = new \Mautic\EmailBundle\EventListener\ReportSubscriber($a, ($container->services['mautic.lead.model.company_report_data'] ?? $container->load('getMautic_Lead_Model_CompanyReportDataService')), ($container->services['Mautic\\EmailBundle\\Entity\\StatRepository'] ?? $container->load('getStatRepository3Service')), $b, $c);
    }
}
