<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportDNCSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\EventListener\ReportDNCSubscriber' shared autowired service.
     *
     * @return \Mautic\LeadBundle\EventListener\ReportDNCSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['router'] ?? $container->getRouterService());

        if (isset($container->services['Mautic\\LeadBundle\\EventListener\\ReportDNCSubscriber'])) {
            return $container->services['Mautic\\LeadBundle\\EventListener\\ReportDNCSubscriber'];
        }
        $b = ($container->services['mautic.channel.helper.channel_list'] ?? $container->getMautic_Channel_Helper_ChannelListService());

        if (isset($container->services['Mautic\\LeadBundle\\EventListener\\ReportDNCSubscriber'])) {
            return $container->services['Mautic\\LeadBundle\\EventListener\\ReportDNCSubscriber'];
        }

        return $container->services['Mautic\\LeadBundle\\EventListener\\ReportDNCSubscriber'] = new \Mautic\LeadBundle\EventListener\ReportDNCSubscriber(($container->services['mautic.lead.reportbundle.fields_builder'] ?? $container->load('getMautic_Lead_Reportbundle_FieldsBuilderService')), ($container->services['mautic.lead.model.company_report_data'] ?? $container->load('getMautic_Lead_Model_CompanyReportDataService')), ($container->services['translator'] ?? $container->getTranslator2Service()), $a, $b);
    }
}
