<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportSubscriber5Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\FormBundle\EventListener\ReportSubscriber' shared autowired service.
     *
     * @return \Mautic\FormBundle\EventListener\ReportSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\FormBundle\\EventListener\\ReportSubscriber'] = new \Mautic\FormBundle\EventListener\ReportSubscriber(($container->services['mautic.lead.model.company_report_data'] ?? $container->load('getMautic_Lead_Model_CompanyReportDataService')), ($container->services['Mautic\\FormBundle\\Entity\\SubmissionRepository'] ?? $container->load('getSubmissionRepositoryService')), ($container->services['Mautic\\FormBundle\\Entity\\FormRepository'] ?? $container->getFormRepositoryService()), ($container->services['mautic.helper.core_parameters'] ?? ($container->services['mautic.helper.core_parameters'] = new \Mautic\CoreBundle\Helper\CoreParametersHelper($container))), ($container->services['translator'] ?? $container->getTranslator2Service()));
    }
}
