<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStageActionChangeTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\StageBundle\Form\Type\StageActionChangeType' shared autowired service.
     *
     * @return \Mautic\StageBundle\Form\Type\StageActionChangeType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\StageBundle\\Form\\Type\\StageActionChangeType'] = new \Mautic\StageBundle\Form\Type\StageActionChangeType();
    }
}
