<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticFocusBundle\EventListener\StatSubscriber' shared autowired service.
     *
     * @return \MauticPlugin\MauticFocusBundle\EventListener\StatSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.focus.model.focus'] ?? $container->getMautic_Focus_Model_FocusService());

        if (isset($container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\StatSubscriber'])) {
            return $container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\StatSubscriber'];
        }

        return $container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\StatSubscriber'] = new \MauticPlugin\MauticFocusBundle\EventListener\StatSubscriber($a, ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
