<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_EventDispatcher_SamlLoginService extends AppKernelProdContainer
{
    /*
     * Gets the private 'security.event_dispatcher.saml_login' shared service.
     *
     * @return \Symfony\Component\EventDispatcher\EventDispatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['security.event_dispatcher.saml_login'] = $instance = new \Symfony\Component\EventDispatcher\EventDispatcher();

        $instance->addListener('Symfony\\Component\\Security\\Http\\Event\\LogoutEvent', [0 => function () use ($container) {
            return ($container->services['mautic.security.logout_handler'] ?? $container->load('getMautic_Security_LogoutHandlerService'));
        }, 1 => 'onSymfonyComponentSecurityHttpEventLogoutEvent'], 0);
        $instance->addListener('security.interactive_login', [0 => function () use ($container) {
            return ($container->services['Mautic\\CoreBundle\\EventListener\\CoreSubscriber'] ?? $container->getCoreSubscriberService());
        }, 1 => 'onSecurityInteractiveLogin'], 0);
        $instance->addListener('Symfony\\Component\\Security\\Http\\Event\\LogoutEvent', [0 => function () use ($container) {
            return ($container->privates['security.logout.listener.csrf_token_clearing'] ?? $container->load('getSecurity_Logout_Listener_CsrfTokenClearingService'));
        }, 1 => 'onLogout'], 0);

        return $instance;
    }
}
