<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authentication_Provider_FosOauthServer_MainService extends AppKernelProdContainer
{
    /*
     * Gets the private 'security.authentication.provider.fos_oauth_server.main' shared service.
     *
     * @return \FOS\OAuthServerBundle\Security\Authentication\Provider\OAuthProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.user.provider'] ?? $container->getMautic_User_ProviderService());

        if (isset($container->privates['security.authentication.provider.fos_oauth_server.main'])) {
            return $container->privates['security.authentication.provider.fos_oauth_server.main'];
        }

        return $container->privates['security.authentication.provider.fos_oauth_server.main'] = new \FOS\OAuthServerBundle\Security\Authentication\Provider\OAuthProvider($a, ($container->privates['fos_oauth_server.server'] ?? $container->load('getFosOauthServer_ServerService')), ($container->privates['security.user_checker'] ?? ($container->privates['security.user_checker'] = new \Symfony\Component\Security\Core\User\InMemoryUserChecker())));
    }
}
