<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStageRepositoryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\StageBundle\Entity\StageRepository' shared autowired service.
     *
     * @return \Mautic\StageBundle\Entity\StageRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\StageBundle\\Entity\\StageRepository'] = new \Mautic\StageBundle\Entity\StageRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
