<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserHashService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\UserBundle\Hash\UserHash' shared autowired service.
     *
     * @return \Mautic\UserBundle\Hash\UserHash
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\UserBundle\\Hash\\UserHash'] = new \Mautic\UserBundle\Hash\UserHash();
    }
}
