<?php

namespace ContainerMOMedhB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserService extends AppKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.8O3g9_t.Mautic\UserBundle\Entity\User' shared service.
     *
     * @return \Mautic\UserBundle\Entity\User
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.8O3g9_t": it references class "Mautic\\UserBundle\\Entity\\User" but no such service exists.');
    }
}
